### ISSUE TITLE
Explore call to action button on Homepage has a broken link

### ISSUE THREAD

**Issue by droynvoss** [dothq/new.dothq.co#29]
### Steps to reproduce
1. Click on the Explore call to action button from the [homepage](https://www.dothq.org/en-US).
<img src="https://user-images.githubusercontent.com/92980894/211362073-3de02a24-6ce9-436f-9627-81eb6822521a.png" alt="drawing" width="690"/>

2. Leads to a `404: Page Not Found` message to the [the browser page](https://www.dothq.org/en-US/browser).
<img src="https://user-images.githubusercontent.com/92980894/211362203-4e5d2ea4-60be-4291-a8d8-d4e4498165f9.png" alt="drawing" width="690"/>

3. Further, all links under the parent [Browser](https://www.dothq.org/en-US/browser) are also met with the same `404: Page Not Found` message.

<br>
<br>

## Consequences
1. Leads to an end user exclusively being able to download from the Github repository to specific devices or requirements.

**Comment by kierandrewett** [comment]
Those pages are still a WIP so that's why it's returning a 404.

**Comment by kierandrewett** [comment]
This particular link has been fixed, closing.
