### ISSUE TITLE
Header text is not scaled properly on Chrome Mobile

### ISSUE THREAD

**Issue by ejaz4** [dothq/new.dothq.co#63]
On Chrome Android, and other browsers, header text (H1, H2, H3 .etc) is not scaled properly and is abnormally large.

An example of which is on the 404 page:
Firefox Mobile:
![Screenshot_20230721-015741.png](https://github.com/dothq/scalar/assets/73548455/04184972-6b11-4043-980d-c47e4d65c99a)
Chrome Mobile:
![Screenshot_20230721-015743](https://github.com/dothq/scalar/assets/73548455/6b3b2fbd-fe35-4405-8bcc-fcd6123ec3dc)

This issue is global across the whole site even on the homepage's heros. 
![Screenshot_20230721-015038](https://github.com/dothq/scalar/assets/73548455/63e52b8c-bc43-414b-9ec5-53882ee1c4ea)

OS: Android 14 (UPB4.230623.005)

**Comment by ejaz4** [comment]
Screenshot for Firefox mobile, I attached the wrong one earlier.

#
![Screenshot_20230721-015741](https://github.com/dothq/scalar/assets/73548455/1d6c9572-e60d-4670-8d15-6ab4573d1f70)

**Comment by kierandrewett** [comment]
On closer inspection, this looks to be intended behaviour.

https://github.com/dothq/scalar/blob/60d5e41288ce828307108be937ef4ae9196973da/ui/foundation/components/typography.scss#L89-L115

I believe I wrote this when WebKit/Blink didn't yet have support for dynamic viewport units so we could just force the baseline font size.

Reverting this change shouldn't break anything as both Chrome and Safari support this now.

**Comment by ejaz4** [comment]
Fixed in https://github.com/dothq/scalar/commit/b69b076c6efcba5d3bc63c1b7e22b29f5a549a63
